// 📦 CATÁLOGO — Exquisiteces (abril 2026)
// Si Supabase está configurado, los productos se cargan desde la DB en tiempo real.
// Este array es el seed inicial y fallback si la conexión falla.

export const PRODUCTOS = [
  // ─── SALADOS ───────────────────────────────
  { id:'pan-nube', nombre:'Pan Nube', categoria:'salado', presentacion:'x6 unid · 150gr', ingredientes:'Huevo, leche en polvo descremada, ajo', precio:5200, precio_30:4900, imagen:'assets/Productos%20salados/pan-nube.jpg', destacado:true, con_stock:true },
  { id:'pizzetas', nombre:'Pizzetas', categoria:'salado', presentacion:'x2 unid · 160gr', ingredientes:'Huevo, leche descremada, salsa pizza, orégano, ajo', precio:5600, precio_30:5300, imagen:'assets/Productos%20salados/pizzetas.jpg', con_stock:true },
  { id:'pan-lomo', nombre:'Pan de Lomo', categoria:'salado', presentacion:'x2 unid · 160gr', ingredientes:'Huevo, leche descremada, ajo, condimento pizza', precio:5500, precio_30:5200, imagen:'assets/Productos%20salados/pan-lomo.jpg', con_stock:true },
  { id:'dalmendra', nombre:"D'Almendra", categoria:'salado', presentacion:'x1 unid rebanada · 340gr', ingredientes:'Huevo, harina de almendras', precio:6500, precio_30:6200, imagen:'assets/Productos%20salados/pan-almendra.jpg', con_stock:true },
  { id:'pan-sesamo', nombre:'Pan de Sésamo', categoria:'salado', presentacion:'x1 unid rebanada · 340gr', ingredientes:'Huevo, leche descremada, semillas de sésamo', precio:6000, precio_30:5700, imagen:'assets/Productos%20salados/Pan%20de%20s%C3%A9samo.jpeg', con_stock:true },
  { id:'palitos-parmesano', nombre:'Palitos de Parmesano', categoria:'salado', presentacion:'x6 unid · 150gr', ingredientes:'Huevo, harina almendras, parmesano, albahaca, manteca', precio:5600, precio_30:5300, imagen:'assets/Productos%20salados/palitos.jpg', con_stock:true },
  { id:'panqueques', nombre:'Panqueques', categoria:'salado', presentacion:'x6 unid', ingredientes:'Huevo, harina de almendras', precio:4800, precio_30:4500, imagen:'assets/Productos%20salados/panqueques.jpg', con_stock:true },

  // ─── DULCES ───────────────────────────────
  { id:'pepas', nombre:'Pepas', categoria:'dulce', presentacion:'x4 unid · 160gr', ingredientes:'H. almendras, huevo, manteca, jalea de frutos rojos, vainilla', precio:6000, precio_30:5700, imagen:'assets/Productos%20dulces/pepas.png', con_stock:true },
  { id:'galletas-jengibre', nombre:'Galletas de Jengibre', categoria:'dulce', presentacion:'x6 unid', ingredientes:'H. almendras, huevo, manteca, canela, jengibre, nuez moscada', precio:5500, precio_30:5200, imagen:'assets/Productos%20dulces/Galletas%20de%20jengibre.jpeg', con_stock:true },
  { id:'pistacho-crunchy', nombre:'Pistacho Crunchy', categoria:'dulce', presentacion:'x2 unid · 140gr', ingredientes:'Pasta pistacho, pistacho, manteca cacao, chocolate blanco S/A', precio:7000, precio_30:6700, imagen:'assets/Productos%20dulces/pistacho-crunchy.jpg', destacado:true, con_stock:true },
  { id:'muffins', nombre:'Muffins', categoria:'dulce', presentacion:'x6 unid · 200gr', ingredientes:'Huevo, coco, cacao amargo, leche descremada (marmolado/naranja/coco)', precio:6100, precio_30:5800, imagen:'assets/Productos%20dulces/Muffins%20marmolados.jpeg', con_stock:true },
  { id:'bizcochuelos', nombre:'Bizcochuelos', categoria:'dulce', presentacion:'x2 unid · 680gr', ingredientes:'H. almendras, huevo, edulcorante, cacao amargo, semillas amapola', precio:6200, precio_30:5900, imagen:'assets/Productos%20dulces/bizcochuelos.jpg', con_stock:true },
  { id:'alfajor-almendra', nombre:'Alfajor de Almendra', categoria:'dulce', presentacion:'x2 unid · 340gr', ingredientes:'H. almendras, dulce de leche stevia, pasta maní, chocolate 70%', precio:6200, precio_30:5900, imagen:'assets/Productos%20dulces/alfajor-almendras.jpg', destacado:true, con_stock:true },
  { id:'alfajor-nevado', nombre:'Alfajor Nevado', categoria:'dulce', presentacion:'x1 unid · 200gr', ingredientes:'Huevo, leche descremada, cacao, DDL stevia, pasta maní, chocolate', precio:5500, precio_30:5200, imagen:null, con_stock:true },
  { id:'bombones-explosivos', nombre:'Bombones Explosivos', categoria:'dulce', presentacion:'x5 unid · 150gr', ingredientes:'DDL stevia, chocolate blanco S/A, chocolate negro 70%', precio:5700, precio_30:5400, imagen:'assets/Productos%20dulces/Bombones.jpeg', con_stock:true },
  { id:'cookies-almendra', nombre:'Cookies de Almendra', categoria:'dulce', presentacion:'x5 unid · 270gr', ingredientes:'H. almendras, huevo, manteca, coco, choco blanco S/A, chocolate 70%', precio:6100, precio_30:5800, imagen:'assets/Productos%20dulces/cookies-almendra.jpeg', con_stock:true },
  { id:'budin-patagonico', nombre:'Budín Patagónico', categoria:'dulce', presentacion:'x1 unid · 510gr', ingredientes:'H. almendras, huevo, manteca, frutos rojos, chocolate rosa', precio:8000, precio_30:7700, imagen:'assets/Productos%20dulces/budin-patagonico.jpg', destacado:true, con_stock:true },
  { id:'budin-manzana', nombre:'Budín de Manzana', categoria:'dulce', presentacion:'x1 unid · 480gr', ingredientes:'Huevo, coco, h. almendras, manzana, canela', precio:5800, precio_30:5500, imagen:'assets/Productos%20dulces/Budin%20de%20manzana.jpeg', con_stock:true },
  { id:'budin-chocolatoso', nombre:'Budín Chocolatoso', categoria:'dulce', presentacion:'x1 unid · 480gr', ingredientes:'H. almendras, huevo, coco, cacao amargo, chocolate blanco S/A, chocolate 70%', precio:6600, precio_30:6300, imagen:'assets/Productos%20dulces/Budin%20chocolatoso.jpeg', con_stock:true },
  { id:'tesoro-frutos-secos', nombre:'Tesoro de Frutos Secos', categoria:'dulce', presentacion:'x1 unid · 500gr', ingredientes:'H. almendras, huevo, coco, nueces, almendras, cajú', precio:7700, precio_30:7400, imagen:'assets/Productos%20dulces/budin-frutos-secos.jpg', con_stock:true },
  { id:'mini-cookies', nombre:'Mini Cookies', categoria:'dulce', presentacion:'x16 unid', ingredientes:'H. almendras, manzana, canela, banana, huevo, chips cacao, avena, dátiles', precio:7600, precio_30:7300, imagen:null, con_stock:true },
  { id:'perlas-pistacho', nombre:'Perlas de Pistacho', categoria:'dulce', presentacion:'x3 unid · 130gr', ingredientes:'Huevo, h. almendras, pistacho, pasta pistacho, coco, ralladura limón', precio:7600, precio_30:7300, imagen:'assets/Productos%20dulces/perlas.png', con_stock:true },
  { id:'donas-rellenas', nombre:'Donas Rellenas', categoria:'dulce', presentacion:'x2 unid · 540gr', ingredientes:'H. almendras, huevo, leche descremada, chocolate negro 70%', precio:6600, precio_30:6300, imagen:'assets/Productos%20dulces/Donas.jpeg', con_stock:true },
  { id:'tarta-cabsha', nombre:'Tarta Cabsha', categoria:'dulce', presentacion:'x1 unid · 260gr', ingredientes:'H. almendras, huevo, coco, DDL stevia, pasta maní, chocolate 70%', precio:5600, precio_30:5300, imagen:'assets/Productos%20dulces/tarta-cabsha.jpg', con_stock:true },
  { id:'lemon-haze', nombre:'Lemon Haze', categoria:'dulce', presentacion:'x1 unid · 160gr', ingredientes:'H. almendras, huevo, manteca, edulcorante, chocolate blanco S/A', precio:5200, precio_30:4900, imagen:'assets/Productos%20dulces/lemon-haze.jpg', con_stock:true },
  { id:'datiles-rellenos', nombre:'Dátiles Rellenos', categoria:'dulce', presentacion:'x5 unid · 180gr', ingredientes:'Dátiles egipcios, pasta maní, chocolate negro 70%, sal himalaya', precio:7900, precio_30:7600, imagen:'assets/Productos%20dulces/datiles.jpg', con_stock:true },
  { id:'brownie', nombre:'Brownie', categoria:'dulce', presentacion:'x1 unid · 200gr', ingredientes:'H. almendras, huevo, manteca, cacao amargo, nueces, pasta maní', precio:5100, precio_30:4800, imagen:'assets/Productos%20dulces/brownie.png', destacado:true, con_stock:true },
  { id:'cuadrado-amor', nombre:'Cuadrado del Amor', categoria:'dulce', presentacion:'x1 unid · 200gr', ingredientes:'H. almendras, huevo, manteca, frambuesas, chocolate blanco S/A', precio:5500, precio_30:5200, imagen:'assets/Productos%20dulces/cuadrado.png', con_stock:true },
  { id:'chocotorta', nombre:'Chocotorta', categoria:'dulce', presentacion:'x1 unid · 340gr', ingredientes:'H. almendras, huevo, queso crema, DDL stevia, edulcorante, chocolate 70%', precio:6600, precio_30:6300, imagen:'assets/Productos%20dulces/chocotorta.jpg', destacado:true, con_stock:true },
  { id:'tiramisu', nombre:'Tiramisú', categoria:'dulce', presentacion:'x1 unid · 340gr', ingredientes:'H. almendras, huevo, queso crema, edulcorante, café, vainilla', precio:6600, precio_30:6300, imagen:null, con_stock:true },
  { id:'barrita-frutos-secos', nombre:'Barrita de Frutos Secos', categoria:'dulce', presentacion:'x1 unid · 100gr', ingredientes:'Avena, miel, gelatina, semillas zapallo/chía, maní, almendras, nueces, cajú, arándanos, chocolate blanco', precio:5100, precio_30:4800, imagen:'assets/Productos%20dulces/Barrita%20de%20frutos%20secos.jpeg', con_stock:true },
  { id:'barrita-proteica', nombre:'Barrita Proteica', categoria:'dulce', presentacion:'x1 unid · 100gr', ingredientes:'Pasta maní, DDL stevia, proteína Star+ vainilla, gelatina, chocolate', precio:5400, precio_30:5100, imagen:'assets/Productos%20dulces/Barritas%20proteicas.jpeg', con_stock:true },

  // ─── LAS QUINAS ───────────────────────────
  { id:'ddl-sa', nombre:'Dulce de Leche S/A', categoria:'quinas', subcategoria:'DDL', presentacion:'500gr · Stevia, libre gluten', ingredientes:'Leche, edulcorante (stevia)', precio:5200, imagen:null, con_stock:true },
  { id:'miel-clasica', nombre:'Miel Clásica', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel pura de abeja', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20clasica.jpeg', con_stock:true },
  { id:'miel-cremosa', nombre:'Miel Cremosa', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel pura cremada', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20cremosa.jpeg', con_stock:true },
  { id:'miel-premium', nombre:'Miel Premium', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel premium seleccionada', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20premium.jpeg', con_stock:true },
  { id:'miel-limon', nombre:'Miel de Limón', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel pura, limón', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20de%20limon.jpeg', con_stock:true },
  { id:'miel-eucalipto', nombre:'Miel de Eucalipto', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel pura de eucalipto', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20de%20eucalipto.jpeg', con_stock:true },
  { id:'miel-cruda', nombre:'Miel Cruda', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel cruda sin filtrar', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20cruda.jpeg', con_stock:true },
  { id:'miel-organica', nombre:'Miel Orgánica Cremosa', categoria:'quinas', subcategoria:'Mieles', presentacion:'500gr · Las Quinas', ingredientes:'Miel orgánica certificada cremada', precio:5600, imagen:'assets/Las%20Quinas/Mieles/Miel%20organica%20liquida.jpeg', con_stock:true },
  { id:'merm-arandanos-sa', nombre:'Mermelada de Arándanos S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Arándanos, edulcorante', precio:5600, imagen:'assets/Las%20Quinas/Mermeladas/Arandanos.jpeg', con_stock:true },
  { id:'merm-frutos-rojos-sa', nombre:'Mermelada de Frutos Rojos S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Frutos rojos, edulcorante', precio:5600, imagen:'assets/Las%20Quinas/Mermeladas/Frutos%20rojos.jpeg', con_stock:true },
  { id:'merm-frutilla-sa', nombre:'Mermelada de Frutilla S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Frutilla, edulcorante', precio:5600, imagen:'assets/Las%20Quinas/Mermeladas/Frutilla.jpeg', con_stock:true },
  { id:'merm-durazno-sa', nombre:'Mermelada de Durazno S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Durazno, edulcorante', precio:5600, imagen:'assets/Las%20Quinas/Mermeladas/Durazno.jpeg', con_stock:true },
  { id:'merm-ciruela-sa', nombre:'Mermelada de Ciruela S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Ciruela, edulcorante', precio:5600, imagen:'assets/Las%20Quinas/Mermeladas/Ciruela.jpeg', con_stock:true },
  { id:'merm-mora-sa', nombre:'Mermelada de Mora S/A', categoria:'quinas', subcategoria:'Mermeladas', presentacion:'420gr · Las Quinas · sin azúcar', ingredientes:'Mora, edulcorante', precio:5600, imagen:null, con_stock:true }
];

export const FOTO_PROXIMAMENTE = `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 400'><defs><pattern id='p' width='20' height='20' patternUnits='userSpaceOnUse'><circle cx='10' cy='10' r='1.2' fill='%23C8185A' opacity='0.18'/></pattern></defs><rect width='400' height='400' fill='%23FCF3F8'/><rect width='400' height='400' fill='url(%23p)'/><circle cx='200' cy='180' r='62' fill='none' stroke='%23C8185A' stroke-width='2.5' stroke-dasharray='6 4'/><text x='200' y='190' text-anchor='middle' font-family='Georgia,serif' font-style='italic' font-size='42' fill='%23C8185A'>E</text><text x='200' y='270' text-anchor='middle' font-family='Georgia,serif' font-style='italic' font-size='20' fill='%232A1320'>foto próximamente</text><text x='200' y='298' text-anchor='middle' font-family='sans-serif' font-size='11' fill='%237E586D' letter-spacing='3'>EXQUISITECES</text></svg>`;
